name: CI Workflow

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Git clone the repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.8.18

            - name: Set up virtual environment
              run: make create-venv

            - name: Install dependencies
              run: |
                source venv/bin/activate
                make install
            
            - name: Run tests
              run: |
                source venv/bin/activate
                make run-tests
            
            - name: Run tests with coverage
              run: |
                source venv/bin/activate
                make run-coverage
            
            - name: Run formatter
              run: |
                  source venv/bin/activate
                  make run-formater

            - name: Run linter
              run: |
                source venv/bin/activate
                make run-lint
