name: CI test workflow

on:
    pull_request:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Git clone the repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.8.18

            - name: Set up virtual environment
              run: make create-venv

            - name: Install dependencies
              run: |
                source venv/bin/activate
                make install
            
            - name: Run tests
              run: |
                source venv/bin/activate
                make run-tests
            
            - name: Run tests with coverage
              run: |
                source venv/bin/activate
                make run-coverage

            - name: Comment coverage
              uses: coroo/pytest-coverage-commentator@v1.0.2
              with:
                pytest-coverage: coverage.txt
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
